workdir:config["workdir"]

rule all:
	input:
		#expand("{sample}/qc/start/StartReportQC_{sample}.html", sample=config["samples"]),
		#expand("{sample}/qc/trimming/trimming_report_{sample}.html", sample=config["samples"]),
		expand("{sample}/qc/filtering/filtering_report_{sample}.html", sample=config["samples"]),
		expand("{sample}/annotation/{sample}.standardardized.gb", sample=config["samples"]) if (config["Standardization"]) else expand("{sample}/annotation/{sample}.original.gb",sample=config["samples"]),
		expand("{sample}/annotation/{sample}.standardardized.fasta", sample=config["samples"]) if (config["Standardization"]) else expand("{sample}/assembly/{sample}.original.fasta",sample=config["samples"]),
		#expand("{sample}/qc/backmapping/{sample}.backmapping.readcoverage.log", sample=config["samples"]),
		

include: "rules/Preprocessing.smk"

include: "rules/Trimming.smk"

include: "rules/Processing.smk"

include: "rules/Assembly.smk"

include: "rules/Annotation.smk"

include: "rules/Backmapping.smk"

localrules: AnnotationPreStandardization, AnnotationPostStandardization
