workdir:config["workdir"]


def allInputFunction(wildcards):
	output = []

	if (config["Trimming"]):
		output += expand("{sample}/01_data/qc/trimming_report_{sample}.html", sample=config["samples"])
	
	output += expand("{sample}/01_data/qc/filtering_report_{sample}.html", sample=config["samples"])

	if (config["Standardization"]):
		output += expand("{sample}/03_annotation/{sample}.standardardized.filt.gb", sample=config["samples"])
	else:
		output += expand("{sample}/03_annotation/{sample}.annotated.filt.gb",sample=config["samples"])

	if (config["Submission"]):
		for i in config["samples"]:
			if i in config["samples_metadata"]:
				output += ["%s/04_submission/%s.submission.gb" %(i,i)]

	if (config["Backmapping"]):
		output += expand("{sample}/04_backmapping/{sample}.backmapping.visualization.html", sample=config["samples"])

	return output

rule all:
	input:
		allInputFunction		


include: "rules/00_Preprocessing.smk"

include: "rules/01_Trimming.smk"

include: "rules/01_Processing.smk"

include: "rules/02_Assembly.smk"

include: "rules/03_Annotation.smk"

include: "rules/04_Backmapping.smk"

include: "rules/04_Submission.smk"

localrules: AnnotationPreStandardization, AnnotationPostStandardization, AnnotationQualityCheck
