cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --qos={resources.qos}
    --time={resources.time}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --error=logs/{rule}/{rule}-{wildcards}-%j.err
    --mail-user=sjannalda@zedat.fu-berlin.de
    --mail-type=end
    --parsable
default-resources:
  - mem_mb=1000
  - time="0-00:05:00"
  - qos="standard"
cluster-status: "/home/sjannalda/bgbm/projects/PlastidPipeline/resources/status-sacct.sh"
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: False