##### Pipeline Options
Trimming: False
Standardization: True
Metadata: False
Backmapping: True


##### Important File Paths

# Working directory where all the analysis will run. This should be in "scratch" or similar folder
workdir: "/scratch/sjannalda/projects/ArnicaProcessing"

# Samples to analyze
samples:
    #spain1: /remote/trove/bgbm/baobab/2018_ArnicaSNP/spain/FASTQ/HFYM3DSX7_1_379UDI-idt-UMI
    #ERR8268641: /scratch/sjannalda/bgbm/data/DownloadedData/ERR8268641/test/ERR8268641
    SRR17032099: /scratch/sjannalda/projects/PlastidPipelineTesting/rawdata/SRR17032099/SRR17032099
    #SRR12917849: /scratch/sjannalda/projects/PlastidPipelineTesting/rawdata/SRR12917849/SRR12917849
    SRR12917857: /scratch/sjannalda/projects/PlastidPipelineTesting/rawdata/SRR12917857/SRR12917857
    #ERR5529317: /scratch/sjannalda/projects/PlastidPipelineTesting/rawdata/ERR5529317/ERR5529317
    #ERR5529436: /scratch/sjannalda/projects/PlastidPipelineTesting/rawdata/ERR5529436/ERR5529436
    #ERR5554746: /scratch/sjannalda/projects/PlastidPipelineTesting/rawdata/ERR5554746/ERR5554746
    #ERR5529299: /scratch/sjannalda/projects/PlastidPipelineTesting/rawdata/ERR5529299/ERR5529299
    #Am09: /scratch/sjannalda/projects/Am09/run1/data/AM0909
    #Am21: /scratch/sjannalda/projects/Am21/run1/data/AM2134
    #SRR17032105: /scratch/sjannalda/projects/PlastidPipelineTesting/rawdata/SRR17032105/SRR17032105
    #SRR12432532: /scratch/sjannalda/projects/PlastidPipelineTesting/rawdata/SRR12432532/SRR12432532

# Metadata full file path for sample to analyze, but only if want to output in format for submission
samples_metadata:
    #SRR12917849: /scratch/sjannalda/projects/SequenceInfoMetadata/SRS7602758_metadata.txt 
    SRR17032099: /scratch/sjannalda/projects/SequenceInfoMetadata/SRS11147532_metadata.txt
    SRR12917857: /scratch/sjannalda/projects/SequenceInfoMetadata/SRS7602750_metadata.txt

# Trimming Adapter File
adapter_trimming_file: "/home/sjannalda/bgbm/projects/PlastidPipeline/config/TruSeq3-PE-2.fa" # Path to adapter file, but you can provide your own file.

# Quality Control Gene List File
plant_genes_file: "/home/sjannalda/bgbm/projects/PlastidPipeline/config/plantgenes.txt" # Full path



##### Parameters for each section of the pipeline

### Filtering Options
MinQualityScore: 30

### Assembly Options 
organelle_database_folder: "database" # Can either provide a path if already made, or it will be created within the workdir
OrganelleDatabasesDownload: "embplant_pt,embplant_mt" # Apparently GetOrganelle needs both of these first before proceeding
OrganelleDatabasesAssembly: "embplant_pt"

# Parameters for GetOrganelle 
KmerSpades: "21,45,65,85,105" #  -k. SPAdes kmer settings
MaxRounds: 30 # -R. Max number of extended rounds. Default is 15 by GetOrganelle
PreGrouped: 1000000 # -P. The maximum number (integer) of high-covered reads to be pre-grouped before extending process. pre_grouping is suggested when the whole genome coverage is shallow but the organ genome coverage is deep

### Annotation Options for GeSeq
GenomeShape: "Linear" # Options: Linear, Circular
SequenceSource: "Land" # Options: Land, Algae, Mito. Refers to Plastid (Land plants), Plastid (algae), or Mitochondria
AnnotateIR: True # Refers to annotate plastid Inverted Repeat (IR)
AnnotateRPS12: True # Refers to annotate plastid trans-spliced rps12
AnnotationChloe: True # Refers to support annotation by Chloë
ChloeAnnotateCDS: True # Refers to annotate CDS from Chloe, is support annotation by Chloe is selected
ChloeAnnotateTRNA: True # Refers to annotation tRNA from Chloe, if support annotation by Chloe is selected
ChloeAnnotateRRNA: False # Refers to annotation rRNA from Chloe, if support annotation by Chloe is selected
AnnotationMFannot: False # Refers to support annotation by MFannot. NOTE: Currently not supported
AnnotationRevision: "Best" # Options: Best, All. Refers to only keep best annotation, or keep all annotations
MPIMP_RefSet: True # Refers to use MPI's reference set of chloroplast land plants (CDS + rRNA)
MultiGenBank: True # Refers to generate multi-GenBank

### Standardization Options
lsc_gene: "rbcL" # Gene located in LSC. Default is "rbcL" (previously used "psbA" with direction -1)
lsc_gene_dir: 1 # Gene direction of lsc. 1 is forward, -1 is reverse
ssc_gene: "ndhF" # Gene located in SSC
ssc_gene_dir: 1 # Gene direction of ssc. 1 is forward, -1 is reverse

### Backmapping Visualization OPtions
MinReadCoverageWarning: 30 # Minimum number of reads for read coverage warning

